name: build-app

on:
  push: 
    branches: [develop]

jobs:
  build-the-app: 
    runs-on: ubuntu-latest
    environment: development
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get environment variables
        run: |
        echo "sumit"
        echo ${{ secrets.SLACK_WEBHOOK_URL }}
        echo ${{ secrets.SLACK_WEBHOOK_URL2 }}